networks:
  users-service-network:
    driver: bridge
  logs-service-network:
    driver: bridge
  orders-service-network:
    driver: bridge
  app-network:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

  kafka-init:
    container_name: kafka-init
    image: confluentinc/cp-kafka:7.0.1
    command: ["/bin/bash", "-c", "/create-topics.sh"]
    environment:
      TOPICS: "logs.central,notifications.central,stock.reserve,stock.echec,order-created,payment.done,inventories.central"
    depends_on:
      kafka:
        condition: service_started
    volumes:
      - type: bind
        source: ./ressources/create-topics.sh
        target: /create-topics.sh
    init: true
    networks:
      - app-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    volumes:
      - ./ressources/kafkaui.yml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - app-network
    depends_on: 
      kafka-init:
        condition: service_completed_successfully

  logs-service-database:
    container_name: logs-service-database
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_root
      - MONGO_INITDB_ROOT_PASSWORD=password_root
    volumes:
      - ./services/logs/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    depends_on: 
      kafka-init:
        condition: service_completed_successfully
    networks:
      - logs-service-network
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--username",
          "admin_root",
          "--password",
          "password_root",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.runCommand({ ping: 1 })",
        ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s

  logs-service:
    container_name: logs-service
    ports:
      - "3000:3000"
    build:
      context: ./services/logs
      dockerfile: Dockerfile
    depends_on:
      logs-service-database:
        condition: service_healthy
    restart: on-failure
    networks:
      - logs-service-network
      - app-network

  users-service-database:
    container_name: users-service-database
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_root
      - MONGO_INITDB_ROOT_PASSWORD=password_root
    volumes:
      - ./services/users/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - users-service-network
    depends_on: 
      kafka-init:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--username",
          "admin_root",
          "--password",
          "password_root",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.runCommand({ ping: 1 })",
        ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s

  users-service:
    container_name: users-service
    ports:
      - "3001:3001"
    build:
      context: ./services/users
      dockerfile: Dockerfile
    depends_on:
      users-service-database:
        condition: service_healthy
    restart: on-failure
    networks:
      - users-service-network
      - app-network

  notifications-service:
    container_name: notifications-service
    build:
      context: ./services/notifications
      dockerfile: Dockerfile
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    restart: on-failure
    networks:
      - app-network

  payments-service:
    container_name: payments-service
    ports:
      - "3002:3002"
    build:
      context: ./services/payments
      dockerfile: Dockerfile
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    restart: on-failure
    networks:
      - app-network

  inventory-service:
    container_name: inventory-service
    build:
      context: ./services/inventories
      dockerfile: Dockerfile
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    restart: on-failure
    networks:
      - app-network
    environment:
      KAFKA_BROKER: kafka:29092
      TOPIC_INVENTORY: inventories.central
      TOPIC_LOGS: logs.central
      KAFKA_GROUP_ID: inventory-group

  orders-service-database:
    container_name: orders-service-database
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_root
      - MONGO_INITDB_ROOT_PASSWORD=password_root
    volumes:
      - ./services/orders/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - orders-service-network
    depends_on: 
      kafka-init:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--username",
          "admin_root",
          "--password",
          "password_root",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.runCommand({ ping: 1 })",
        ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s

  orders-service:
    container_name: orders-service
    build:
      context: ./services/orders
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      orders-service-database:
        condition: service_healthy
    restart: on-failure
    networks:
      - orders-service-network
      - app-network

  skate-shop-frontend:
    build: ./frontend
    container_name: skate-shop-frontend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      logs-service:
        condition: service_started
      users-service:
        condition: service_started
      notifications-service:
        condition: service_started
      payments-service:
        condition: service_started
      inventory-service:
        condition: service_started
      orders-service:
        condition: service_started
